; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:custom-board]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D CUSTOM_BOARD
	; Suppress the lmic_project_config.h file — configure via build_flags instead
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS

    ; Radio type — RFM95 uses the SX1276
    -D CFG_sx1276_radio=1

    ; Region — pick ONE:
    ;-D CFG_eu868=1    ; Europe
    -D CFG_us915=1  ; USA
    ; -D CFG_au915=1  ; Australia
    ; -D CFG_as923=1  ; Asia

    ; Class A only — saves memory by disabling unused features
    -D DISABLE_PING
    -D DISABLE_BEACONS


lib_deps =
	ropg/ezTime@^0.8.3
	bblanchon/ArduinoJson@^7.1.0
	mcci-catena/MCCI Arduino LoRaWAN Library
    adafruit/Adafruit ADS1X15@^2.6.2

[env:long-range]
extends = env:custom-board
build_flags = ${env:custom-board.build_flags} -DLONG_RANGE

[env:long-range-debug]
extends = env:custom-board
build_flags = ${env:long-range.build_flags} -DDEBUG_LORA